'use client';

import { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  SendHorizontal, 
  Image as ImageIcon, 
  X, 
  Loader2,
  Sparkles
} from 'lucide-react';
import { toast } from 'sonner';

interface MessageInputProps {
  onSend: (message: string, image?: string) => void;
  isLoading: boolean;
  isVisionCapable: boolean;
}

export default function MessageInput({ onSend, isLoading, isVisionCapable }: MessageInputProps) {
  const [text, setText] = useState('');
  const [image, setImage] = useState<string | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto';
      textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`;
    }
  }, [text]);

  const handleSend = () => {
    if (!text.trim() && !image) return;
    onSend(text, image || undefined);
    setText('');
    setImage(null);
  };

  const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (file.size > 5 * 1024 * 1024) {
      toast.error('Image is too large (max 5MB)');
      return;
    }

    if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type)) {
      toast.error('Only jpeg, png, and webp images are allowed.');
      return;
    }

    const reader = new FileReader();
    reader.onloadend = () => {
      setImage(reader.result as string);
    };
    reader.readAsDataURL(file);
  };

  return (
    <div className="relative w-full max-w-4xl px-4 pb-8 space-y-4">
      <AnimatePresence>
        {image && (
          <motion.div 
            initial={{ opacity: 0, y: 10, scale: 0.9 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 10, scale: 0.9 }}
            className="absolute bottom-full mb-4 group"
          >
            <div className="relative h-24 w-24 overflow-hidden rounded-xl border border-accent/50 shadow-2xl">
              <img src={image} alt="Preview" className="h-full w-full object-cover" />
              <button 
                onClick={() => setImage(null)}
                className="absolute top-1 right-1 rounded-full bg-black/50 p-1 text-white hover:bg-black transition-all"
              >
                <X className="h-3 w-3" />
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      <div className="relative flex items-end gap-2 rounded-2xl border border-border-custom bg-surface p-2 shadow-2xl focus-within:border-accent/50 transition-all">
        {isVisionCapable && (
          <div className="flex items-center pb-2 pl-2">
            <button
              onClick={() => fileInputRef.current?.click()}
              className="rounded-lg p-2 text-muted hover:bg-base hover:text-white transition-all"
              title="Add Image"
            >
              <ImageIcon className="h-5 w-5" />
            </button>
            <input 
              type="file" 
              ref={fileInputRef} 
              onChange={handleImageUpload} 
              className="hidden" 
              accept="image/jpeg,image/png,image/webp"
            />
          </div>
        )}

        <textarea
          ref={textareaRef}
          rows={1}
          value={text}
          onChange={(e) => setText(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === 'Enter' && !e.shiftKey) {
              e.preventDefault();
              handleSend();
            }
          }}
          placeholder="Type your message..."
          className="flex-1 max-h-60 min-h-[44px] bg-transparent py-3 px-3 text-sm text-text-custom outline-none resize-none scrollbar-none"
        />

        <div className="pb-1.5 pr-1.5 flex items-center gap-2">
          {isLoading ? (
            <div className="rounded-xl bg-accent/20 p-2.5 text-accent shadow-sm animate-pulse">
              <Loader2 className="h-5 w-5 animate-spin" />
            </div>
          ) : (
            <button
              onClick={handleSend}
              disabled={!text.trim() && !image}
              className={`rounded-xl p-2.5 text-white transition-all shadow-lg ${
                (!text.trim() && !image) ? 'bg-muted cursor-not-allowed' : 'bg-accent hover:bg-accent-dim shadow-accent/20'
              }`}
            >
              <SendHorizontal className="h-5 w-5" />
            </button>
          )}
        </div>
      </div>
      
      <p className="text-center text-[10px] text-muted flex items-center justify-center gap-1 selection:bg-accent/20">
        <Sparkles className="h-3 w-3" />
        AI outputs are generated by Cortexa's open-source weights. Verify if critical.
      </p>
    </div>
  );
}
